"""Standalone HTML for the Cursor usage and routing dashboard."""

from __future__ import annotations

from .dashboard_styles import DASHBOARD_CSS


CURSOR_DASHBOARD_HTML = r"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Cursor 用量与路由面板</title>
  <style>
    :root{--bg:#080b12;--panel:#111722;--panel2:#151d2b;--line:#263247;--text:#edf3ff;--muted:#91a0b8;--accent:#75a7ff;--cyan:#66d9e8;--purple:#b58cff;--good:#66dda0;--warn:#ffbd66;--bad:#ff6f7d}
    *{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 0,#18233a 0,transparent 28%),var(--bg);color:var(--text);font:14px/1.45 Inter,Segoe UI,Arial,sans-serif}.shell{max-width:1680px;margin:auto;padding:16px}.top{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:14px}.brand h1{font-size:22px;margin:0 0 4px;letter-spacing:-.3px}.muted,.subtitle,.small{color:var(--muted)}.small{font-size:12px}.nav{display:inline-flex;padding:3px;background:#0d1420;border:1px solid var(--line);border-radius:10px;margin-bottom:10px}.nav a{color:var(--muted);text-decoration:none;padding:6px 13px;border-radius:7px}.nav a.active{color:var(--text);background:var(--panel2)}
    .status{flex-shrink:0;white-space:nowrap;display:flex;align-items:center;gap:9px;background:#111927cc;border:1px solid var(--line);padding:7px 10px;border-radius:12px}.dot{width:9px;height:9px;border-radius:50%;background:var(--good);box-shadow:0 0 12px var(--good)}button,input{font:inherit;color:var(--text);background:#0d1420;border:1px solid var(--line);border-radius:9px;padding:7px 9px;outline:none}button{cursor:pointer}button:hover,button.active{border-color:var(--accent);background:#17243a}.error{display:none;margin:0 0 12px;background:#341720;border:1px solid #71313d;color:#ffadb5;padding:11px;border-radius:10px}
    .panel,.card{background:linear-gradient(145deg,#141c2a,#0f1520);border:1px solid var(--line);border-radius:15px;box-shadow:0 16px 40px #0003}.panel{min-width:0;padding:14px;margin-bottom:12px}.panel h2{font-size:15px;margin:0 0 11px}.cards{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px;margin-bottom:12px}.card{padding:12px;min-width:0}.card .label{color:var(--muted);font-size:11px}.card .value{font-size:22px;font-weight:730;margin-top:5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.card .hint{font-size:11px;color:var(--muted);margin-top:2px}.unit{font-size:10px;font-weight:400;color:var(--muted);margin-left:4px}
    .filters{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.filters label{color:var(--muted);font-size:12px}.spacer{flex:1}.grid{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(0,1fr);gap:10px;margin-bottom:12px}.chart{min-height:210px;display:flex;align-items:stretch;gap:7px;overflow-x:auto;padding-top:8px}.day-col{display:flex;flex-direction:column;align-items:center;justify-content:flex-end;gap:5px;min-width:46px;flex:1}.day-bars{height:150px;width:34px;display:flex;align-items:flex-end;justify-content:center;gap:3px}.vbar{width:14px;min-height:2px;border-radius:4px 4px 0 0}.chart-label{font-size:10px;color:var(--muted);white-space:nowrap}.legend{display:flex;justify-content:center;gap:14px;flex-wrap:wrap;color:var(--muted);font-size:12px}.legend-dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:5px}.line-chart{overflow-x:auto;min-height:210px}.model-row{display:grid;grid-template-columns:minmax(110px,190px) 1fr 105px;align-items:center;gap:10px;margin:10px 0}.bar-track{height:9px;border-radius:9px;background:#090d14;overflow:hidden}.bar-fill{height:100%;border-radius:9px;background:linear-gradient(90deg,var(--accent),var(--purple))}.right{text-align:right}
    .scroll{overflow:auto;max-height:54vh;border:1px solid var(--line);border-radius:10px}table{width:100%;border-collapse:collapse;min-width:900px}th{position:sticky;top:0;background:#111925;color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.04em;text-align:left;padding:8px 10px;border-bottom:1px solid var(--line);z-index:1}td{padding:8px 10px;border-bottom:1px solid #202a3a;vertical-align:top}tbody tr:hover{background:#172131}.title-cell{max-width:360px;overflow-wrap:anywhere}.pill{display:inline-flex;border:1px solid var(--line);background:#0b111b;border-radius:99px;padding:3px 8px;font-size:12px;white-space:nowrap}.good{color:var(--good)}.warn{color:var(--warn)}.bad{color:var(--bad)}.empty{padding:34px;text-align:center;color:var(--muted)}.top-list{display:grid;gap:7px}.top-item{display:grid;grid-template-columns:28px 1fr auto;gap:9px;align-items:center;padding:8px 0;border-bottom:1px solid var(--line)}.rank{display:grid;place-items:center;width:24px;height:24px;border-radius:50%;background:#1b2940;color:var(--accent);font-weight:700}.footer{display:flex;justify-content:space-between;gap:12px;color:var(--muted);font-size:12px;margin-top:10px}
    @media(max-width:1100px){.cards{grid-template-columns:repeat(3,1fr)}.grid{grid-template-columns:minmax(0,1fr)}}@media(max-width:650px){.shell{padding:10px}.top{align-items:flex-start;flex-direction:column}.cards{grid-template-columns:repeat(2,1fr)}.model-row{grid-template-columns:100px 1fr 85px}.footer{flex-direction:column}.spacer{display:none}}
__SHARED_DASHBOARD_CSS__
.panel{margin-bottom:0}.usage-filters{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:16px}.chart-box h2{font-size:15px}.card .value{white-space:normal;overflow:visible}.chart{min-height:0;height:195px;padding-top:0}.line-chart{min-height:0}.status{white-space:normal;flex-shrink:1}.unit{font-size:10px}.usage-tools{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:8px 0}.route-distribution-row{display:grid;grid-template-columns:minmax(95px,1fr) minmax(45px,1.3fr) 90px;gap:7px;align-items:center;margin:10px 0}.route-distribution-row .small{font-size:11px}.scroll{border:0;border-radius:0;max-height:56vh}
  </style>
</head>
<body><main class="shell">
  <nav class="nav" aria-label="面板切换"><a href="./">Codex</a><a href="cursor" class="active" aria-current="page">Cursor</a></nav>
  <header class="top"><div class="brand"><h1>Cursor 用量与路由面板</h1><div class="subtitle">Token 来自官方导出快照，模型路由来自本地日志 · <a href="https://cursor.com/dashboard/usage" target="_blank" rel="noopener noreferrer" style="color:var(--accent)">前往 Cursor 官方用量页导出</a></div></div><div class="status"><span class="dot" id="dot"></span><span id="status">正在连接</span><button id="refresh">立即刷新</button></div></header>
  <div id="error" class="error" role="alert"></div>
  <section class="panel" style="margin-bottom:20px">
    <h2>Cursor · Token 用量</h2>
    <div class="usage-filters"><button data-days="0">今天</button><button data-days="7">最近 7 天</button><button data-days="15">最近 15 天</button><button data-days="30">最近 30 天</button><button data-days="all">全部记录</button><label>从 <input id="start" type="date"></label><label>至 <input id="end" type="date"></label><button id="apply">查询</button></div>
    <div class="usage-tools small"><span id="usageSummary"></span><label title="CSV 仅发送至本机接口"><input id="csvFile" type="file" accept=".csv,text/csv" style="max-width:210px"> 导入官方 CSV</label></div>
    <section class="cards" id="usageCards" style="margin-top:16px"></section>
    <div style="display:flex;align-items:center;justify-content:space-between;gap:12px"><h2 style="margin:0">用量图表</h2><select id="usageMetric" aria-label="图表指标"><option value="total_tokens">总用量（输入 + 输出）</option><option value="input_tokens">输入 Token</option><option value="output_tokens">输出 Token</option><option value="uncached_input_tokens">未缓存输入</option></select></div>
    <div class="chart-grid"><article class="chart-box"><h2>每日用量趋势</h2><div id="dailyChart" class="trend"></div><div id="dailyLegend" class="legend" style="margin-top:14px"></div></article><article class="chart-box"><h2>输入缓存占比</h2><div id="cacheDonut"></div></article><article class="chart-box"><h2>Cursor 评估器 · 模型分布</h2><div id="routeDistributionNote" class="small"></div><div id="routeDistribution"></div></article></div>
    <article class="chart-box" style="margin-bottom:12px"><h2>每日输入缓存命中率</h2><div id="cacheTrend" class="line-chart"></div></article>
    <article class="chart-box" style="margin-bottom:18px"><h2>模型用量对比</h2><div id="modelChart"></div></article>
    <p class="small">官方快照暂不支持按对话统计和推理 Token 明细。</p>
  </section>
  <h2 style="font-size:18px">模型路由</h2>
  <section class="cards" id="routeCards"></section>
  <section class="panel"><h2>模型路由记录</h2><p class="small">期望模型与实际模型分别展示；实际模型为空时标记为待核验，不计为成功或匹配。</p><div id="routes" class="scroll"></div></section>
  <footer class="footer"><span id="coverage"></span><span id="updated"></span></footer>
</main><script>
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const known=value=>value!==null&&value!==undefined&&value!==''&&Number.isFinite(Number(value));
const numeric=value=>known(value)?Number(value):null;
const number=value=>known(value)?new Intl.NumberFormat('zh-CN').format(Number(value)):'—';
function token(value){const n=numeric(value);if(n===null)return '—';const a=Math.abs(n);if(a>=1e8)return `${(n/1e8).toFixed(2)} 亿`;if(a>=1e4)return `${(n/1e4).toFixed(2)} 万`;return new Intl.NumberFormat('zh-CN').format(n)}
function ratio(value){const n=numeric(value);return n===null?'—':`${(Math.max(0,Math.min(1,n))*100).toFixed(1)}%`}
function dateTime(value){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.getTime())?'—':d.toLocaleString('zh-CN',{hour12:false})}
function total(row){const direct=numeric(row?.total_tokens);if(direct!==null)return direct;const input=numeric(row?.input_tokens),output=numeric(row?.output_tokens);return input===null||output===null?null:input+output}
function metricTitle(row){return `输入 ${token(row.input_tokens)} Token · 输出 ${token(row.output_tokens)} Token · 缓存 ${token(row.cached_input_tokens)} Token`}
function renderCards(summary={}){const cards=[['输入 Token',summary.input_tokens,'包含缓存输入'],['缓存输入',summary.cached_input_tokens,`命中率 ${ratio(summary.cache_hit_rate)}`],['未缓存输入',summary.uncached_input_tokens,'输入减去缓存'],['输出 Token',summary.output_tokens,'包含推理输出'],['缓存写入',summary.cache_write_input_tokens,'已包含在输入中']];$('usageCards').innerHTML=cards.map(([label,value,hint],i)=>`<article class="card"><div class="label">${esc(label)}</div><div class="value" title="${esc(number(value))+' Token'}">${esc(token(value))}${'<span class="unit">Token</span>'}</div><div class="hint">${esc(hint)}</div></article>`).join('')}
let usageData=null;
function modelColor(model){const name=String(model);if(name.startsWith('composer-'))return name.endsWith('-fast')?'var(--purple)':'var(--accent)';if(name.startsWith('cursor-grok'))return 'var(--cyan)';let hash=0;for(const c of name)hash=(hash*31+c.charCodeAt(0))>>>0;return `hsl(${hash%360} 60% 65%)`}
function renderDaily(rows=[]){const k=$('usageMetric').value,valid=rows.filter(r=>known(r[k])).sort((a,b)=>String(a.date).localeCompare(String(b.date))),host=$('dailyChart'),max=Math.max(1,...valid.map(r=>r[k]));host.innerHTML=valid.map(r=>`<div class="trend-col" title="${esc(r.date)} · ${esc(token(r[k]))} Token"><span class="chart-label">${token(r[k])}</span><div class="trend-bar" style="height:${r[k]/max*145}px;display:flex;flex-direction:column-reverse;overflow:hidden;background:transparent">${(r.models||[]).map(m=>`<div style="height:${r[k]?m[k]/r[k]*100:0}%;background:${modelColor(m.model)};flex-shrink:0" title="${esc(m.model)}：${token(m[k])} Token"></div>`).join('')}</div><span class="chart-label">${esc(r.date.slice(5))}</span></div>`).join('')||'<span class="muted">所选时间内没有记录</span>';$('dailyLegend').innerHTML=(usageData?.by_model||[]).map(m=>`<span><i class="legend-dot" style="background:${modelColor(m.model)}"></i>${esc(m.model)}</span>`).join('')}
function renderDonut(s){const rate=numeric(s.cache_hit_rate);$('cacheDonut').innerHTML=`<div class="donut" style="background:conic-gradient(var(--luna) ${(rate||0)*100}%,var(--line) 0)"><div class="donut-center">${ratio(rate)}<span class="small">输入缓存命中率</span></div></div><div class="legend"><span>命中 ${token(s.cached_input_tokens)}</span><span>未缓存 ${token(s.uncached_input_tokens)}</span></div>`}
function renderCacheTrend(rows=[]){const valid=rows.filter(r=>r.date&&known(r.cache_hit_rate)).sort((a,b)=>String(a.date).localeCompare(String(b.date))),host=$('cacheTrend');if(!valid.length){host.innerHTML='<div class="empty">所选日期内没有缓存命中率数据</div>';return}const width=Math.max(500,valid.length*42),height=205,left=42,right=16,top=18,bottom=34;const stamp=i=>Date.parse(valid[i].date+'T00:00:00Z'),first=stamp(0),last=stamp(valid.length-1);const x=i=>first===last?width/2:left+(stamp(i)-first)/(last-first)*(width-left-right);const rates=valid.map(r=>r.cache_hit_rate),lo=Math.min(...rates),hi=Math.max(...rates),pad=Math.max(.005,(hi-lo)*.15),axisMin=Math.max(0,Math.floor((lo-pad)*100)/100),axisMax=Math.min(1,Math.ceil((hi+pad)*100)/100);const y=v=>top+(axisMax-v)/(axisMax-axisMin)*(height-top-bottom);const grid=Array.from({length:5},(_,i)=>axisMin+(axisMax-axisMin)*i/4).map(v=>`<line x1="${left}" x2="${width-right}" y1="${y(v)}" y2="${y(v)}" stroke="var(--line)"/><text x="${left-6}" y="${y(v)+4}" text-anchor="end" fill="var(--muted)" font-size="10">${Number((v*100).toFixed(2))}%</text>`).join('');const path=valid.map((r,i)=>`${i?'L':'M'}${x(i)},${y(r.cache_hit_rate)}`).join(' ');const step=Math.max(1,Math.ceil(valid.length/10));host.innerHTML=`<svg viewBox="0 0 ${width} ${height}" style="display:block;width:100%;min-width:${Math.min(width,500)}px" aria-label="每日输入缓存命中率，Y轴自动缩放 ${ratio(axisMin)} 至 ${ratio(axisMax)}">${grid}<path d="${path}" fill="none" stroke="var(--cyan)" stroke-width="2.5"/>${valid.map((r,i)=>`<circle cx="${x(i)}" cy="${y(r.cache_hit_rate)}" r="4" fill="var(--cyan)"><title>${esc(r.date)}：${ratio(r.cache_hit_rate)}</title></circle>`).join('')}${valid.filter((_,i)=>i%step===0||i===valid.length-1).map(r=>`<text x="${x(valid.indexOf(r))}" y="${height-10}" text-anchor="middle" fill="var(--muted)" font-size="10">${esc(String(r.date).slice(5))}</text>`).join('')}</svg>`}
function renderModels(rows=[]){const k=$('usageMetric').value,sorted=[...rows].sort((a,b)=>(b[k]??-1)-(a[k]??-1)),max=Math.max(1,...sorted.map(r=>r[k]||0));$('modelChart').innerHTML=sorted.map(row=>`<div class="model-chart-row" title="${esc(metricTitle(row))}"><span class="small">${esc(row.model||'未知模型')}</span><div class="bar-track"><div class="bar-fill" style="width:${(row[k]||0)/max*100}%;background:${modelColor(row.model)}"></div></div><span class="right chart-label">${token(row[k])} Token</span></div>`).join('')||'<span class="muted">所选时间内没有记录</span>'}

function table(head,body,colspan){return `<table><thead><tr>${head.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${body||`<tr><td colspan="${colspan}" class="empty">暂无数据</td></tr>`}</tbody></table>`}
function renderRouteDistribution(rows=[]){
const counts=new Map(['composer-2.5','composer-2.5-fast','cursor-grok-4.6-high'].map(model=>[model,0]));let total=0;
rows.forEach(row=>{if(row.requested_model&&!String(row.reason||'').startsWith('error:')){counts.set(row.requested_model,(counts.get(row.requested_model)||0)+1);total++}});
$('routeDistributionNote').textContent=`Composer 2.5 评估 · ${$('start').value||'最早记录'} 至 ${$('end').value||'最新记录'} · 共 ${number(total)} 次选模`;
$('routeDistribution').innerHTML=[...counts].map(([model,count])=>{const share=total?count/total:0,color=model.startsWith('composer-')?(model.endsWith('-fast')?'var(--purple)':'var(--accent)'):'var(--cyan)';return `<div class="route-distribution-row"><span class="small" style="overflow-wrap:anywhere;color:${color}">${esc(model)}</span><div class="bar-track"><div class="bar-fill" style="width:${share*100}%;background:${color}"></div></div><span class="small right">${number(count)} · ${ratio(share)}</span></div>`}).join('');
}
function routeState(row){if(String(row.reason||'').startsWith('error:'))return ['评估失败','bad'];if(row.actual_model===null||row.actual_model===undefined||row.actual_model==='')return ['待核验','warn'];if(row.requested_model===null||row.requested_model===undefined||row.requested_model==='')return ['已核验','good'];return String(row.actual_model)===String(row.requested_model)?['匹配','good']:['不匹配','bad']}
function renderRoutes(rows=[],summary={}){const values=[['路由总数',summary.total,'所选日期'],['已核验',summary.verified,'存在实际模型'],['期望匹配',summary.matched,'实际等于期望'],['失败 / 不匹配',summary.failed,'评估失败或实际模型不匹配']];$('routeCards').innerHTML=values.map(([label,value,hint])=>`<article class="card"><div class="label">${esc(label)}</div><div class="value">${esc(number(value))}</div><div class="hint">${esc(hint)}</div></article>`).join('');const body=rows.map(row=>{const [label,cls]=routeState(row);return `<tr><td>${esc(dateTime(row.timestamp))}</td><td>${esc(row.original_model||'—')}</td><td>${esc(row.requested_model||'—')}</td><td>${esc(row.actual_model||'—')}</td><td><span class="pill ${cls}">${label}</span></td><td class="title-cell">${esc(row.reason||'—')}</td><td>${esc(row.id||'—')}</td></tr>`}).join('');$('routes').innerHTML=table(['时间','原始模型','期望模型','实际模型','核验状态','原因','ID'],body,7)}
function render(data){usageData=data;renderDonut(data.summary||{});$('usageSummary').textContent=`输入 + 输出：${token(data.summary?.total_tokens)} Token · 官方导出快照`;renderCards(data.summary||{});renderDaily(data.by_day||[]);renderCacheTrend(data.by_day||[]);renderModels(data.by_model||[]);renderRouteDistribution(data.routes||[]);renderRoutes(data.routes||[],data.route_summary||{});const c=data.coverage||{};$('coverage').textContent=`Token 为官方导出快照。导入时间：${dateTime(c.imported_at)}；数据日期：${c.event_range?.start||'—'} 至 ${c.event_range?.end||'—'}；跳过缺失行 ${number(c.invalid_rows)}、自带 API Key 行 ${number(c.skipped_api_key_rows)}。`;$('updated').textContent=`更新：${new Date().toLocaleString('zh-CN',{hour12:false})}`}
$('usageMetric').onchange=()=>{if(usageData){renderDaily(usageData.by_day||[]);renderModels(usageData.by_model||[])}};
let requestSeq=0;
async function load(){const seq=++requestSeq,query=new URLSearchParams();if($('start').value)query.set('start',$('start').value);if($('end').value)query.set('end',$('end').value);$('status').textContent='正在刷新';try{const response=await fetch(`api/cursor?${query}`,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();if(seq!==requestSeq)return;render(data);$('error').style.display='none';$('dot').style.background='var(--good)';$('status').textContent='页面每 30 秒刷新'}catch(error){if(seq!==requestSeq)return;$('error').textContent=`Cursor 面板读取失败：${error.message}`;$('error').style.display='block';$('dot').style.background='var(--bad)';$('status').textContent='连接异常'}}
async function importCsv(file){if(!file)return;if(file.size>20*1024*1024){$('error').textContent='CSV 导入失败：文件不能超过 20 MB';$('error').style.display='block';$('csvFile').value='';return}$('status').textContent='正在导入官方 CSV';try{const content=await file.text(),response=await fetch('api/cursor/import',{method:'POST',headers:{'Content-Type':'text/csv'},body:content});if(!response.ok){const raw=await response.text();let detail=raw;try{detail=JSON.parse(raw).error||raw}catch(_error){}throw new Error(detail||`HTTP ${response.status}`)}$('error').style.display='none';$('status').textContent='导入成功，正在刷新';await load()}catch(error){$('error').textContent=`CSV 导入失败：${error.message}`;$('error').style.display='block';$('dot').style.background='var(--bad)';$('status').textContent='导入失败'}finally{$('csvFile').value=''}}
function localDate(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function period(value){const today=new Date(),start=new Date(today);if(value==='all'){$('start').value='';$('end').value=''}else{const days=Number(value);start.setDate(start.getDate()-Math.max(0,days-1));$('start').value=localDate(start);$('end').value=localDate(today)}document.querySelectorAll('[data-days]').forEach(button=>button.classList.toggle('active',button.dataset.days===String(value)));load()}
document.querySelectorAll('[data-days]').forEach(button=>button.onclick=()=>period(button.dataset.days));$('apply').onclick=()=>{document.querySelectorAll('[data-days]').forEach(button=>button.classList.remove('active'));load()};$('refresh').onclick=load;$('csvFile').onchange=event=>importCsv(event.target.files?.[0]);period('0');setInterval(load,30000);
</script></body></html>""".replace("__SHARED_DASHBOARD_CSS__", DASHBOARD_CSS)
